# Build stage
FROM node:20-alpine as build

WORKDIR /app

# Add pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy package files and install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

# Copy the rest of the code
COPY . .

# Build the application
ARG VITE_API_URL=/api
ENV VITE_API_URL=${VITE_API_URL}
RUN pnpm build

# Production stage
FROM nginx:1.25-alpine

# Copy build files from previous stage
COPY --from=build /app/dist /usr/share/nginx/html

# Use custom nginx config if you have one
# COPY nginx.conf /etc/nginx/nginx.conf

# Default command
CMD ["nginx", "-g", "daemon off;"]